### PR TITLE
fix: use GNU or BSD sed depending on the system

### PR DESCRIPTION
**Pull request by delehef**

### CODE REVIEW

**Review by RyanRHall — APPROVED** [review]
LGTM 👍

**Comment by delehef** [comment]
@RyanRHall have you tested it? It does not work for Kais.

**Comment by RyanRHall** [comment]
@delehef @kaisbaccour seems to work on my machine - Kais are you on linex? what errors do you see?

**Comment by RyanRHall** [comment]
@delehef made a small tweak, should work now!

**Comment by RyanRHall** [comment]
No longer relevant after switching to awk [here](https://github.com/Lagrange-Labs/lagrange-lpn-contracts/pull/55)

**Pull request closed without merging**
